services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # optional, for connecting from host (psql, DBeaver, etc.)

  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 appsite.asgi:application
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=django_db
      - DB_USER=django_user
      - DB_PASSWORD=django_pass
      - USE_POSTGRES=true
      - POPULATE_MOCK_DATA=true # Set to true to populate mock data on startup
    develop:
      watch:
        - action: sync
          path: ./appsite
          target: /code/appsite
        - action: sync
          path: ./manage.py
          target: /code/manage.py
        - action: rebuild
          path: ./requirements.txt
        - action: sync
          path: .
          target: /code
          ignore:
            - db.sqlite3
            - __pycache__/
            - .git/
            - node_modules/
            - .venv/
            - venv/
            - templates/
  frontend:
    build:
      context: ./frontend
    command: npm start
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true # helps hot reload in Docker on macOS

volumes:
  postgres_data:
